# Generated by Django 4.0.4 on 2022-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermodel_lessonsmax_alter_usermodel_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='pathimg',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
