# Generated by Django 4.0.4 on 2022-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermodel_pathimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pathimg',
            field=models.CharField(default="{% static 'img/arrow_l.svg'%}", max_length=1000),
        ),
    ]
