# Generated by Django 4.0.4 on 2022-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermodel_pathimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pathimg',
            field=models.CharField(default='img/user.svg', max_length=1000),
        ),
    ]
